quarkus.http.port=8082
quarkus.application.name=client-service

quarkus.smallrye-health.root-path=/api/health

#CONFIGURACION OPENTELEMETRY
quarkus.otel.enabled=true
quarkus.otel.instrument.rest=true

#MICROMETER PARA @TIMED y @COUNTED
#quarkus.micrometer.enabled=true
#quarkus.micrometer.registry-enabled-default=true
#quarkus.micrometer.export.prometheus.enabled=true
#quarkus.micrometer.export.prometheus.path=/metrics

# Endpoint de métricas (por defecto es /q/metrics; lo movemos a /metrics)
quarkus.smallrye-metrics.path=/metrics

# (Opcional) Etiquetas globales para todas las métricas MP
mp.metrics.tags=app=client-service,env=local

# (Opcional) Métricas del pool de conexiones (Agroal)
quarkus.datasource.metrics.enabled=true
