quarkus.http.port=8082
quarkus.application.name=client-service

#quarkus.hibernate-orm.sql-load-script=import.sql
#quarkus.hibernate-orm.log.sql=true
quarkus.smallrye-health.root-path=/api/health

#CONFIGURACION OPENTELEMETRY
quarkus.otel.enabled=true
quarkus.otel.instrument.rest=true
#MICROMETER PARA @TIMED y @COUNTED
quarkus.micrometer.enabled=true
quarkus.micrometer.registry-enabled-default=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics
